# Numpy recap: Quick demo

In [1]:
import numpy as np

Create a numpy array:

In [ ]:
twodim = np.random.random((30, 5))
onedim = np.arange(1,20,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

Explore attributes:

In [ ]:
twodim.ndim
twodim.size
twodim.shape

2

Access elements:

In [ ]:
twodim[(1,1)]

np.float64(0.32933211538864615)

Slicing:

In [53]:
onedim[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1])

In [ ]:
twodim[::3,2::]

array([[0.1370569 , 0.59228408, 0.89708335],
       [0.09591691, 0.05782673, 0.48942376],
       [0.1438307 , 0.68058721, 0.73424574],
       [0.46737874, 0.8643945 , 0.7637335 ],
       [0.57691252, 0.71777388, 0.71796174],
       [0.63072758, 0.63927996, 0.59360097],
       [0.22124695, 0.25867264, 0.76008572],
       [0.65613586, 0.16448413, 0.34580792],
       [0.69258264, 0.14203097, 0.54587417],
       [0.59281624, 0.14830724, 0.39822955]])

Ufuncs / aggregates

In [26]:
%timeit multiplied = np.multiply(onedim, 2)

596 ns ± 9.24 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [27]:
%timeit multiplied = onedim*2

562 ns ± 21.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [ ]:
np.sum(twodim, axis=0)

array([17.72986009, 14.93145922, 12.2605142 , 14.1823472 , 18.27022691])

In [ ]:
%timeit sum(twodim)
%timeit np.sum(twodim)

11.6 μs ± 414 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
1.42 μs ± 13.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


Boolean masks:

In [29]:
onedim

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [30]:
onedim < 10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False])

In [31]:
selected = onedim[onedim<10]

In [32]:
selected

array([1, 2, 3, 4, 5, 6, 7, 8, 9])